### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by gkbrk** [duncandean/rust-genetic-algorithm#4]
The project should have a license file (usually named LICENSE). There are plenty of open-source license choices but I suggest the [MIT License](http://opensource.org/licenses/MIT).

**Comment by duncandean** [comment]
Alright. You can get one on if you wish or I'll do it later. Make yourself a copyright holder as well, Gökberk.

**Comment by gkbrk** [comment]
All right, added a license file. #5
